# Generated by Django 5.2.8 on 2025-11-23 09:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('booking_date', models.DateField(auto_now=True)),
                ('done_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_num', models.AutoField(primary_key=True, serialize=False)),
                ('departure', models.DateTimeField(default=datetime.datetime.now)),
                ('arrival', models.DateTimeField(default=datetime.datetime.now)),
                ('flight_date', models.DateField(default=datetime.datetime.now)),
                ('flight_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.crew')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.booking')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.flight')),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=2)),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.passenger'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='FirstApp.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='FirstApp.city')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.route'),
        ),
    ]
