# Generated by Django 5.2.8 on 2025-11-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='done_status',
            new_name='paid',
        ),
    ]
