# Generated by Django 5.2.8 on 2025-11-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_alter_booking_total_cost_alter_flight_flight_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
    ]
