# Generated by Django 5.2.8 on 2025-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_rename_done_status_booking_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
