# Generated by Django 5.2.8 on 2025-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
    ]
