# Generated by Django 5.2.8 on 2025-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_alter_booking_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pending',
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
