# Generated by Django 5.2.8 on 2025-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_remove_booking_pending_booking_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
