# Generated by Django 5.2.8 on 2025-11-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middle_initial',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
