# Generated by Django 5.2.8 on 2025-11-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='booking',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='middle_initial',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.item')),
            ],
        ),
    ]
