# Generated by Django 5.2.8 on 2025-11-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_alter_passenger_middle_initial'),
        ('FirstApp', '0008_remove_item_quantity_request_quantity'),
    ]

    operations = [
    ]
